Contact-Register/Models/ContactModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Contact_Register.Models
{
    public class ContactModel
    {
        public int Id { get; set; } 
        [Required(ErrorMessage = "Name is required!")] 
        public string? Name { get; set; }

        [Required(ErrorMessage = "Email is required!")]
        [EmailAddress(ErrorMessage = "You must enter a valid email!")]
        public string? Email { get; set; }
        
        [Required(ErrorMessage = "Smartphone number is required!")]
        [Phone(ErrorMessage = "You must enter a valid smartphone number!")]
        public string? Smartphone { get; set; }
    }
}

Contact-Register/Models/ErrorViewModel.cs
namespace Contact_Register.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

Contact-Register/Models/UserModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using Contact_Register.Enums;
using Microsoft.AspNetCore.Mvc;

namespace Contact_Register.Models
{
    public class UserModel
    {
        public int Id {get; set;}

        [Required(ErrorMessage = "Name is required!")]
        public string? Name { get; set; }

        [Required(ErrorMessage = "Login is required!")]
        [StringLength(25, ErrorMessage = "Login can have a maximum of 25 digits!")]
        public string? Login { get; set; }

        [Required(ErrorMessage = "Email is required!")]
        [EmailAddress(ErrorMessage = "You must enter a valid email!")]
        public string? Email { get; set; }

        [Required(ErrorMessage = "Profile is required!")]
        public Profile Profile { get; set; }

        [Required(ErrorMessage = "Password is required!")]
        [StringLength(25, ErrorMessage = "Password can have a maximum of 25 digits!")]
        public string? Password { get; set; }

        public DateTime Created { get; set; }
        public DateTime? Updated { get; set; }
    }
}

Contact-Register/Controllers/ContactsController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Contact_Register.Models;
using Contact_Register.Repository;

namespace Contact_Register.Controllers;

public class ContactsController : Controller
{
    readonly IContactRepository _contactRepository;
    public ContactsController(IContactRepository contactRepository)
    {
        _contactRepository = contactRepository;
    }
    public IActionResult Index()
    {
        return View(_contactRepository.Get());
    }

    public IActionResult Insert()
    {
        return View();
    }

    public IActionResult Update(int id)
    {
        return View(_contactRepository.GetById(id));
    }

    public IActionResult Delete(int id)
    {
        return View(_contactRepository.GetById(id));
    }

    [HttpPost]
    public IActionResult Insert(ContactModel contact)
    {
        try
        {
            if (ModelState.IsValid)
            {
                _contactRepository.Insert(contact);
                TempData["SuccessAlert"] = "Contact registered successfully!";
                return RedirectToAction("Index");
            }

            return View(contact);
        }
        catch (Exception error)
        {
            TempData["DangerAlert"] = $"Unable to register contact! Error:{error.Message}";
            return RedirectToAction("Index");
        }
    }

    [HttpPost]
    public IActionResult Update(ContactModel contact)
    {
        try
        {
            if (ModelState.IsValid)
            {
                _contactRepository.Update(contact);
                TempData["SuccessAlert"] = "Contact edited successfully!";
                return RedirectToAction("Index");
            }

            return View(contact);
        }
        catch (Exception error)
        {
            TempData["DangerAlert"] = $"Unable to edit this contact! Error:{error.Message}";
            return RedirectToAction("Index");
        }
    }

    public IActionResult Remove(ContactModel contact)
    {
        try
        {
            if (_contactRepository.Remove(contact)) TempData["SuccessAlert"] = "Contact removed successfully!";
            return RedirectToAction("Index");
        }
        catch (Exception error)
        {
            TempData["SuccessAlert"] = $"Unable do remove this contact! {error.Message}";
            return RedirectToAction("Index");
        }
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

Contact-Register/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Contact_Register.Models;

namespace Contact_Register.Controllers;

public class HomeController : Controller
{
    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Contacts()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

Contact-Register/Controllers/UsersController.cs
using System.Diagnostics;
using Contact_Register.Models;
using Contact_Register.Repository;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace Contact_Register.Controllers;

public class UsersController : Controller
{
    readonly IUserRepository _userRepository;
    public UsersController(IUserRepository userRepository)
    {
        _userRepository = userRepository;
    }
    public IActionResult Index()
    {
        return View(_userRepository.Get());
    }

    public IActionResult Insert()
    {
        return View();
    }

    public IActionResult Update(int id)
    {
        return View(_userRepository.GetById(id));
    }

    public IActionResult Delete(int id)
    {
        return View(_userRepository.GetById(id));
    }

    [HttpPost]
    public IActionResult Insert(UserModel user)
    {
        try
        {
            if (ModelState.IsValid)
            {
                _userRepository.Insert(user);
                TempData["SuccessAlert"] = "User registered successfully!";
                return RedirectToAction("Index");
            }

            return View(user);
        }
        catch (Exception error)
        {
            TempData["DangerAlert"] = $"Unable to register user! Error:{error.Message}";
            return RedirectToAction("Index");
        }
    }

    [HttpPost]
    public IActionResult Update(UserModel user)
    {
        try
        {
            if (ModelState.IsValid)
            {
                _userRepository.Update(user);
                TempData["SuccessAlert"] = "User edited successfully!";
                return RedirectToAction("Index");
            }

            return View(user);
        }
        catch (Exception error)
        {
            TempData["DangerAlert"] = $"Unable to edit this user! {error.Message}";
            return RedirectToAction("Index");
        }
    }

    public IActionResult Remove(UserModel user)
    {
        try
        {
            if (_userRepository.Remove(user)) TempData["SuccessAlert"] = "User removed successfully!";
            return RedirectToAction("Index");
        }
        catch (Exception error)
        {
            TempData["SuccessAlert"] = $"Unable do remove this user! {error.Message}";
            return RedirectToAction("Index");
        }
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

Contact-Register/Views/Contacts/Delete.cshtml
@model ContactModel
@{
  ViewData["Title"] = "Erase Contact";
}

<div class="d-flex flex-column align-item-center justify-content-center text-center">
  <h3 class="d-inline-block">
    Do you really want to erase <span class="text-primary">@Model.Name</span>?
  </h3>

  <div class="gap-1" role="group" aria-label="Confirm contact erase group buttons">
    <a role="button" class="btn btn-danger rounded" asp-controller="Contacts" asp-action="Index"><p class="d-inline-block mb-0"><i class="bi bi-x-circle"></i></p></a>
    <a role="button" class="btn btn-success rounded" asp-route-id="@Model.Id" asp-controller="Contacts"
      asp-action="Remove"><p class="d-inline-block mb-0"><i class="bi bi-check-circle"></i></p></a>
  </div>
</div>

Contact-Register/Views/Contacts/Index.cshtml
@model List<ContactModel>
@{
  ViewData["Title"] = "List of Contacts";
}

@if (TempData["SuccessAlert"] != null)
{
  <div class="alert alert-success" role="alert">
  <a class="close-alert btn btn-success rounded d-inline-block position-absolute top-50 end-0 translate-middle-y me-3"><i
      class="bi bi-check-circle"></i></a>
  <p class="mb-0">@TempData["SuccessAlert"]</p>
  </div>
}

@if (TempData["DangerAlert"] != null)
{
  <div class="alert alert-danger" role="alert">
  <a class="close-alert btn btn-danger rounded d-inline-block position-absolute top-50 end-0 translate-middle-y me-3"><i
      class="bi bi-exclamation-circle"></i></a>
  <p class="mb-0">@TempData["DangerAlert"]</p>
  </div>
}

<div>
  @* button to insert a new contact *@
  <a role="button" class="btn btn-outline-primary" asp-controller="Contacts" asp-action="Insert"><i
      class="bi bi-plus-circle"></i></a>
</div>

<h1 class="text-center my-4 h1">Contacts List</h1>

<table class="table hover stripe" id="contact-list-table">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Name</th>
      <th scope="col">Email</th>
      <th scope="col">Smartphone</th>
      <th scope="col"></th>
    </tr>
  </thead>
  <tbody>
    @if (Model != null && Model.Any())
    {
      @foreach (var item in Model)
      {
        <tr class="align-middle">
          <th scope="row">@item.Id</th>
          <td>@item.Name</td>
          <td>@item.Email</td>
          <td>@item.Smartphone</td>
          <td>
            <div class="btn-group gap-2" role="group" aria-label="edit and delete contact list button group">
              <a role="button" class="btn btn-warning rounded d-flex gap-1" asp-route-id="@item.Id"
                asp-controller="Contacts" asp-action="Update"><i class="bi bi-pencil d-inline-block"></i></a>
              <a role="button" class="btn btn-danger rounded d-flex gap-1 text-black" asp-route-id="@item.Id"
                asp-controller="Contacts" asp-action="Delete"><i class="bi bi-trash3"></i></a>
            </div>
          </td>
        </tr>
      }
    }
    else
    {
      <tr class="align-middle">
        <th>
        <td class="text-danger">There are no Contacts!</td>
        <td class="text-danger">There are no Contacts!</td>
        <td class="text-danger">There are no Contacts!</td>
        <td class="text-danger">There are no Contacts!</td>
        <td class="text-danger"></td>
        </th>
      </tr>
    }
  </tbody>
</table>

Contact-Register/Views/Contacts/Insert.cshtml
@model ContactModel
@{
  ViewData["Title"] = "New Contact";
}

<h2 class="text-center">Add new contact</h2>

<form asp-controller="Contacts" asp-action="Insert" method="post">
  
  <div class="form-group mb-2">
    <label for="new-contact-name">Name <span class="text-danger">*</span></label>
    <input asp-for="Name" type="text" class="form-control" id="new-contact-name" aria-describedby="name-help"
      placeholder="Name" required>
    <small class="text-danger">@Html.ValidationMessageFor(x => x.Name)</small>
  </div>
  <div class="form-group mb-2">
    <label for="new-contact-email">Email address <span class="text-danger">*</span></label>
    <input asp-for="Email" type="email" class="form-control" id="new-contact-email" aria-describedby="email-help" placeholder="Email" required>
    <small class="text-danger">@Html.ValidationMessageFor(x => x.Email)</small>
    <small id="email-help" class="form-text text-muted" style="font-size: 0.65rem;">We'll never share your email with anyone else.</small>
  </div>
  <div class="form-group mb-2">
    <label for="new-contact-smartphone">Smartphone <span class="text-danger">*</span></label>
    <input asp-for="Smartphone" type="tel" class="form-control" id="new-contact-smartphone" aria-describedby="smartphone-help" placeholder="Smartphone" pattern="[0-9]{2}[0-9]{2}[0-9]{9}" required>
    <small class="text-danger">@Html.ValidationMessageFor(x => x.Smartphone)</small>
    <small class="text-muted" style="font-size: 0.65rem;">Fromat: XXDDNNNNNNNNN</small> <br>
    <small class="text-muted" style="font-size: 0.65rem;">XX: Country Code -</small>
    <small class="text-muted" style="font-size: 0.65rem;">DD: State Code -</small>
    <small class="text-muted" style="font-size: 0.65rem;">NNNNNNNNN: Smartphone Number</small>
  </div>

  <button type="submit" class="btn btn-outline-success d-flex gap-1" id="new-contact-button"><p class="d-inline-block mb-0"><i class="bi bi-check-circle"></i></p></button>
</form>

Contact-Register/Views/Contacts/Update.cshtml
@model ContactModel
@{
  ViewData["Title"] = "Edit Contact";
}

<h2 class="text-center">Edit contact</h2>

<form asp-controller="Contacts" asp-action="Update" method="post">

  <div class="form-group mb-2">
    <label for="new-contact-name">Name <span class="text-danger">*</span></label>
    <input asp-for="Name" type="text" class="form-control" id="new-contact-name" aria-describedby="name-help"
      placeholder="Name" required>
    <small class="text-danger">@Html.ValidationMessageFor(x => x.Name)</small>
  </div>
  <div class="form-group mb-2">
    <label for="new-contact-email">Email address <span class="text-danger">*</span></label>
    <input asp-for="Email" type="email" class="form-control" id="new-contact-email" aria-describedby="email-help"
      placeholder="Email" required>
    <small class="text-danger">@Html.ValidationMessageFor(x => x.Email)</small>
    <small id="email-help" class="form-text text-muted" style="font-size: 0.65rem;">We'll never share your email with
      anyone else.</small>
  </div>
  <div class="form-group mb-2">
    <label for="new-contact-smartphone">Smartphone <span class="text-danger">*</span></label>
    <input asp-for="Smartphone" type="tel" class="form-control" id="new-contact-smartphone"
      aria-describedby="smartphone-help" placeholder="Smartphone" pattern="[0-9]{2}[0-9]{2}[0-9]{9}" required>
    <small class="text-danger">@Html.ValidationMessageFor(x => x.Smartphone)</small>
    <small class="text-muted" style="font-size: 0.65rem;">Fromat: XXDDNNNNNNNNN</small> <br>
    <small class="text-muted" style="font-size: 0.65rem;">XX: Country Code -</small>
    <small class="text-muted" style="font-size: 0.65rem;">DD: State Code -</small>
    <small class="text-muted" style="font-size: 0.65rem;">NNNNNNNNN: Smartphone Number</small>
  </div>

  <button type="submit" class="btn btn-outline-success d-flex gap-1">
    <p class="d-inline-block mb-0"><i class="bi bi-check-circle"></i></p>
  </button>
</form>

Contact-Register/Views/Home/Index.cshtml
@{
  ViewData["Title"] = "Home Page";
}

<div class="text-center">
  <h1 class="display-4">Welcome!</h1>
  <p>Contact's Register System</p>
</div>


Contact-Register/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Contact's Register</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
    <link href="https://cdn.datatables.net/v/dt/dt-1.13.6/datatables.min.css" rel="stylesheet">
</head>

<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid align-items-end">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Contact's Register</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between mt-2">
                    <ul class="navbar-nav flex-grow-1 gap-2">
                        <li class="nav-item">
                            <a id="nav-item--home" class="nav-link text-light btn btn-primary d-flex gap-1 px-3 py-2" asp-area=""
                                asp-controller="Home" asp-action="Index"><i class="bi bi-house "></i></a>
                        </li>
                        <li class="nav-item">
                            <a id="nav-item--contacts" class="nav-link text-light btn btn-primary d-flex gap-1 px-3 py-2" asp-area=""
                                asp-controller="Contacts" asp-action="Index"><i class="bi bi-card-list"></i></a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light btn btn-primary d-flex gap-1 px-3 py-2" asp-area=""
                                asp-controller="Users" asp-action="Index"><i class="bi bi-person"></i></a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container-fluid">
            &copy; <span id="current_year">@DateTime.Now.Year</span> - Contact's Register
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdn.datatables.net/v/dt/dt-1.13.6/datatables.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>

</html>

Contact-Register/Views/Users/Delete.cshtml
@model UserModel
@{
  ViewData["Title"] = "Erase Contact";
}

<div class="d-flex flex-column align-item-center justify-content-center text-center">
  
  <h3 class="d-inline-block">
    Do you really want to erase <span class="text-primary">@Model.Name</span>?
  </h3>

  <div class="gap-1" role="group" aria-label="Confirm contact erase group buttons">
    <a role="button" class="btn btn-danger rounded" asp-controller="Users" asp-action="Index"><p class="d-inline-block mb-0"><i class="bi bi-x-circle"></i></p></a>
    <a role="button" class="btn btn-success rounded" asp-route-id="@Model.Id" asp-controller="Users"
      asp-action="Remove"><p class="d-inline-block mb-0"><i class="bi bi-check-circle"></i></p></a>
  </div>
  
</div>

Contact-Register/Views/Users/Index.cshtml
@using System.Globalization;
@model List<UserModel>
@{
  ViewData["Title"] = "List of Users";
}

@if (TempData["SuccessAlert"] != null)
{
  <div class="alert alert-success" role="alert">
  <a class="close-alert btn btn-success rounded d-inline-block position-absolute top-50 end-0 translate-middle-y me-3"><i
      class="bi bi-check-circle"></i></a>
  <p class="mb-0">@TempData["SuccessAlert"]</p>
  </div>
}

@if (TempData["DangerAlert"] != null)
{
  <div class="alert alert-danger" role="alert">
  <a class="close-alert btn btn-danger rounded d-inline-block position-absolute top-50 end-0 translate-middle-y me-3"><i
      class="bi bi-exclamation-circle"></i></a>
  <p class="mb-0">@TempData["DangerAlert"]</p>
  </div>
}

<div>
  @* button to insert a new contact *@
  <a role="button" class="btn btn-outline-primary" asp-controller="Users" asp-action="Insert"><i
      class="bi bi-plus-circle"></i></a>
</div>

<h1 class="text-center my-4 h1">Users List</h1>

<table class="table hover stripe" id="user-list-table">

  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Name</th>
      <th scope="col">Email</th>
      <th scope="col">Login</th>
      <th scope="col">Profile</th>
      <th scope="col">Created</th>
      <th scope="col">Updated</th>
      <th scope="col"></th>
    </tr>
  </thead>

  <tbody>
    @if (Model != null && Model.Any())
    {

      @foreach (var item in Model)
      {
        <tr class="align-middle">
          <th scope="row">@item.Id</th>
          <td>@item.Name</td>
          <td>@item.Email</td>
          <td>@item.Login</td>
          <td>@item.Profile</td>
          <td>@item.Created.ToString(CultureInfo.CurrentCulture)</td>
          <td>@item.Updated?.ToString(CultureInfo.CurrentCulture)</td>
          <td>
            <div class="btn-group gap-2" role="group" aria-label="edit and delete contact list button group">
              <a role="button" class="btn btn-warning rounded d-flex gap-1" asp-route-id="@item.Id" asp-controller="Users"
                asp-action="Update"><i class="bi bi-pencil d-inline-block"></i></a>
              <a role="button" class="btn btn-danger rounded d-flex gap-1 text-black" asp-route-id="@item.Id"
                asp-controller="Users" asp-action="Delete"><i class="bi bi-trash3"></i></a>
            </div>
          </td>
        </tr>
      }
    }
    else
    {
      <tr class="align-middle">
        <th>
        <td class="text-danger">There are no Users!</td>
        <td class="text-danger">There are no Users!</td>
        <td class="text-danger">There are no Users!</td>
        <td class="text-danger">There are no Users!</td>
        <td class="text-danger">There are no Users!</td>
        <td class="text-danger"></td>
        </th>
      </tr>
    }
  </tbody>

</table>

Contact-Register/Views/Users/Insert.cshtml
@using Contact_Register.Enums;
@model UserModel
@{
  ViewData["Title"] = "New Contact";
}

<h2 class="text-center">Add new user</h2>

<form asp-controller="Users" asp-action="Insert" method="post">

  <div class="form-group mb-2">
    <label for="new-user-name">Name <span class="text-danger">*</span></label>
    <input asp-for="Name" type="text" class="form-control" id="new-user-name" aria-describedby="name-help"
      placeholder="Name" required>
    <small class="text-danger">@Html.ValidationMessageFor(x => x.Name)</small>
  </div>

  <div class="form-group mb-2">
    <label for="new-user-login">Login <span class="text-danger">*</span></label>
    <input asp-for="Login" type="text" class="form-control" id="new-user-login" aria-describedby="email-help"
      placeholder="Login" required>
    <small class="text-danger">@Html.ValidationMessageFor(x => x.Login)</small>
  </div>

  <div class="form-group mb-2">
    <label for="new-user-email">Email address <span class="text-danger">*</span></label>
    <input asp-for="Email" type="email" class="form-control" id="new-user-email" aria-describedby="email-help"
      placeholder="Email" required>
    <small class="text-danger">@Html.ValidationMessageFor(x => x.Email)</small>
    <small id="email-help" class="form-text text-muted" style="font-size: 0.65rem;">We'll never share your email with
      anyone else.</small>
  </div>

  <div class="form-group mb-2">
    <label for="new-user-profile">Profile <span class="text-danger">*</span></label>
    <select asp-for="Profile" class="form-control" id="new-user-profile" placeholder="Role" required>
      @foreach (var role in Enum.GetValues<Profile>().Reverse())
      {
        <option value="@role">@role</option>
      }
    </select>
    <small class="text-danger">@Html.ValidationMessageFor(x => x.Profile)</small>
  </div>

  <div class="form-group mb-2">
    <label for="new-user-password">Password <span class="text-danger">*</span></label>
    <input asp-for="Password" type="password" class="form-control" id="new-user-password" aria-describedby="email-help"
      placeholder="Type your password" required>
    <small class="text-danger">@Html.ValidationMessageFor(x => x.Password)</small>
  </div>

  <button type="submit" class="btn btn-outline-success d-flex gap-1" id="new-user-button">
    <p class="d-inline-block mb-0"><i class="bi bi-check-circle"></i></p>
  </button>
</form>

Contact-Register/Views/Users/Update.cshtml
@using Contact_Register.Enums;
@model UserModel
@{
  ViewData["Title"] = "Edit Contact";
}

<h2 class="text-center">Edit user</h2>

<form asp-controller="Users" asp-action="Update" method="post">

  <div class="form-group mb-2">
    <label for="new-contact-name">Name <span class="text-danger">*</span></label>
    <input asp-for="Name" type="text" class="form-control" id="new-user-name" aria-describedby="name-help"
      placeholder="Name" required>
    <small class="text-danger">@Html.ValidationMessageFor(x => x.Name)</small>
  </div>

  <div class="form-group mb-2">
    <label for="new-contact-login">Login <span class="text-danger">*</span></label>
    <input asp-for="Login" type="text" class="form-control" id="new-user-login" aria-describedby="email-help"
      placeholder="Login" required>
    <small class="text-danger">@Html.ValidationMessageFor(x => x.Login)</small>
  </div>

  <div class="form-group mb-2">
    <label for="new-contact-email">Email <span class="text-danger">*</span></label>
    <input asp-for="Email" type="email" class="form-control" id="new-user-email" aria-describedby="email-help"
      placeholder="Email" required>
    <small class="text-danger">@Html.ValidationMessageFor(x => x.Email)</small>
    <small id="email-help" class="form-text text-muted" style="font-size: 0.65rem;">We'll never share your email with
      anyone else.</small>
  </div>

  <div class="form-group mb-2">
    <label for="new-user-profile">Profile <span class="text-danger">*</span></label>
    <select asp-for="Profile" class="form-control" id="new-user-profile" placeholder="Role" required>
      @foreach (var role in Enum.GetValues<Profile>().Reverse())
      {
        <option value="@role">@role</option>
      }
    </select>
    <small class="text-danger">@Html.ValidationMessageFor(x => x.Profile)</small>
  </div>

  <div class="form-group mb-2">
    <label for="new-user-password">Password <span class="text-danger">*</span></label>
    <input asp-for="Password" type="password" class="form-control" id="new-user-password" aria-describedby="email-help"
      placeholder="Type your password" required>
    <small class="text-danger">@Html.ValidationMessageFor(x => x.Password)</small>
  </div>

  <button type="submit" class="btn btn-outline-success d-flex gap-1">
    <p class="d-inline-block mb-0"><i class="bi bi-check-circle"></i></p>
  </button>

</form>